apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: admin
  namespace: flux-system
spec:
  postBuild:
    substitute:
      ENVIRONMENT: "sbox"
      CLUSTER: "01"
      WI_CLUSTER: "01"
      WI_NAME: "admin"
      WI_ENVIRONMENT: "sbox"