apiVersion: managedidentity.azure.com/v1api20220131preview
kind: FederatedIdentityCredential
metadata:
  name: test-test-fic
  namespace: admin
spec:
  owner:
    name: test-test-mi
  audiences:
    - api://AzureADTokenExchange
  issuer: test
  subject: system:serviceaccount:test:test
