apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  path: ./clusters/sds/sbox/01
  postBuild:
    substitute:
      CLUSTER: "01"
      ENVIRONMENT: "sbox"
      ENV_MONITOR_CHANNEL: "aks-monitor-sbox"
      ISSUER_URL: "https://uksouth.oic.prod-aks.azure.com/531ff96d-0ae9-462a-8d2d-bec7c0b42082/76d8b2e6-6ce0-44cf-94cf-bbeafa79c4fb"
      KEYVAULT_ENVIRONMENT: "sbox"
      TENANT: "sds"
      WI_ENVIRONMENT: "sbox"
      WI_CLUSTER: "sbox-01"

