apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenants
  namespace: flux-system
spec:
  interval: 
  serviceAccountName: kustomize-controller
  decryption:
    provider: sops
  path: ./clusters/${TENANT}/${ENVIRONMENT}/${CLUSTER}
  sourceRef:
    kind: GitRepository
    name: admin-flux-config
  prune: true
  postBuild:
    substitute:
      ENVIRONMENT: "${ENVIRONMENT}"
      CLUSTER: "\"${CLUSTER}\""
      CLUSTER_PATH: "${ENVIRONMENT}/${CLUSTER}"
      CLUSTER_FULL_NAME: "${ENVIRONMENT}-${CLUSTER}"
      ISSUER_URL: "${ISSUER_URL:-not-set-yet}"
      KEYVAULT_ENVIRONMENT: "${KEYVAULT_ENVIRONMENT}"
      WI_NAME: "flux-system"
      WI_ENVIRONMENT: "${WI_ENVIRONMENT:-not-set-yet}"
      NAMESPACE: "flux-system"