---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/${TENANT}/${ENVIRONMENT}/${CLUSTER}
  prune: false
  sourceRef:
    kind: GitRepository
    name: admin-flux-config
  postBuild:
    substitute:
      ENVIRONMENT: "${ENVIRONMENT}"
      CLUSTER: "\"${CLUSTER}\""
      CLUSTER_PATH: "${ENVIRONMENT}/${CLUSTER}"
      CLUSTER_FULL_NAME: "${ENVIRONMENT}-${CLUSTER}"
      ISSUER_URL: "${ISSUER_URL:-not-set-yet}"
      KEYVAULT_ENVIRONMENT: "${KEYVAULT_ENVIRONMENT}"
      WI_NAME: "${WI_NAME:-not-set-yet}"
      WI_ENVIRONMENT: "${WI_ENVIRONMENT:-not-set-yet}"
      NAMESPACE: "flux-system"
      WI_CLUSTER: "01"
